In [2]:
import numpy as np 
from collections import Counter
from sklearn.datasets import load_iris 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [16]:
def dist(x_train,test_point):
    d=[]
    for i in x_train:
        euc_d=np.sqrt(np.sum((test_point-i)**2)) #euclidean distance
        d.append(euc_d)
    return d

In [4]:
def predict_single(x_train,y_train,test_point,k):
    d=dist(x_train,test_point) #get distances
    sorted_ind=np.argsort(d)
    k_nearest=[]
    for i in range(k):
        k_nearest.append(y_train[sorted_ind[i]])
    label_cnt=Counter(k_nearest)
    most_common_label=label_cnt.most_common(1)[0][0]
    return most_common_label

In [5]:
def predict(x_train,y_train,x_test,k):
    predi=[]
    for i in x_test:
        label=predict_single(x_train,y_train,i,k)
        predi.append(label)
    return predi

In [17]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
k=1
y_pred=predict(x_train,y_train,x_test,k)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test,y_pred,target_names=iris.target_names))
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Accuracy:100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [18]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
k=2
y_pred=predict(x_train,y_train,x_test,k)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test,y_pred,target_names=iris.target_names))
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Accuracy:100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [19]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
k=3
y_pred=predict(x_train,y_train,x_test,k)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test,y_pred,target_names=iris.target_names))
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Accuracy:100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [20]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
k=4
y_pred=predict(x_train,y_train,x_test,k)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test,y_pred,target_names=iris.target_names))
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Accuracy:100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [21]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
k=5
y_pred=predict(x_train,y_train,x_test,k)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test,y_pred,target_names=iris.target_names))
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Accuracy:100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [22]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
k=6
y_pred=predict(x_train,y_train,x_test,k)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test,y_pred,target_names=iris.target_names))
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Accuracy:100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [23]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
k=7
y_pred=predict(x_train,y_train,x_test,k)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test,y_pred,target_names=iris.target_names))
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Accuracy:96.67%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.89      0.94         9
   virginica       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

Confusion Matrix
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]


In [24]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
k=8
y_pred=predict(x_train,y_train,x_test,k)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test,y_pred,target_names=iris.target_names))
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Accuracy:100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [25]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
k=9
y_pred=predict(x_train,y_train,x_test,k)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test,y_pred,target_names=iris.target_names))
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Accuracy:100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [26]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
k=10
y_pred=predict(x_train,y_train,x_test,k)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test,y_pred,target_names=iris.target_names))
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Accuracy:100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
